language: go
go:
  - 1.11.3
script: "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: kEjZw2Cwnoq4zQK2+MwKqUffbrSNEUtXn6GpeoCwqz/sPTOmARcIWD5CKDaYgYWr8weC3ZKPNzVsHH0RwChcGMxckzDyHS7+zxg6D4D8jpaWXC5rsYsVnINA+qoh/6uxY7umQwFU/eYHUKYrs5vNt6phzVjwZ9waxeKFY+jFBdQCrtWuD9gOl1Gp0FXwaDqOocyOiqlINiZFyJZxK+BY0UZ12UzGKAa5EXY56DCwDzFFSF5zoPyHCOIwr2UKb9cpPJNLX/Z0M4r1uvrKt1I8i6vW3lKcHSuK8xKgriaOQU3AsQRC+EXE1UBQNW4ZMXV8teGAbQUDajaD+anqhuJE2Dk6NQhnhy/QYLDW0f4kowdgneE8Ikajd/OoEVSQn8mDalMS6M0iQXPWnC+WQxRi+SwQ/YCUFkURcY5WFdZeg7Grj1vlhWYXte4KVTp/tSVwJlMRvmd1y22j4OQ8rcTb4Fu2JHbLsrNqDtTjQ7aj0ah9XYK9VILftx/dII5COqZD9x1zpNLT+lCSVMjTcmyClqkEid0X+PS4bKREjkIehU2LgKJUQSjAXgdmGV4zvhJYBq/f0GFFBpyBdf7GjqjuMnt7wYxLAtbiaTJSO2148gFzvDveR8fs1u+cae8ss3WhDUVz1su5MEMxQymS9Rvru36yXjNb0tZEZ6LKJFCCLeM=
  file_glob: true
  file: dist/*.tar.gz
  skip_cleanup: true
  on:
    repo: kadaan/smartthings_exporter
    tags: true
